import verificaLE
le = verificaLE.LE()
le.leitorLendo(1)
le.leitorLendo(3)
le.leitorLendo(2)
le.leitorLendo(1)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
le.leitorLendo(2)
le.leitorLendo(4)
le.leitorLendo(3)
# A variavel vale 0
# A variavel vale 0
# A variavel vale 0
le.leitorSaindo(3)
le.escritorBloqueado(3)
le.leitorSaindo(1)
le.escritorBloqueado(1)
le.leitorSaindo(2)
le.escritorBloqueado(2)
# A variavel eh par.
# A variavel eh par.
# A variavel eh par.
le.leitorSaindo(2)
le.leitorSaindo(3)
le.leitorSaindo(1)
# A variavel eh par.
le.leitorSaindo(4)
le.escritorEscrevendo(3)
le.escritorSaindo(3)
le.escritorEscrevendo(2)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
le.escritorBloqueado(3)
le.escritorBloqueado(1)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.leitorBloqueado(1)
le.escritorBloqueado(1)
le.escritorBloqueado(3)
le.escritorBloqueado(1)
le.escritorSaindo(2)
le.leitorLendo(1)
le.escritorBloqueado(1)
le.escritorBloqueado(3)
le.escritorBloqueado(1)
le.leitorLendo(2)
# A variavel eh par.
le.leitorSaindo(1)
# A variavel eh par.
le.leitorSaindo(2)
le.escritorEscrevendo(1)
le.leitorBloqueado(3)
le.escritorSaindo(1)
le.escritorEscrevendo(3)
le.leitorBloqueado(3)
le.escritorBloqueado(1)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.escritorSaindo(3)
le.leitorLendo(3)
le.escritorBloqueado(3)
le.leitorLendo(1)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
le.leitorLendo(2)
# A variavel vale 3
le.leitorSaindo(2)
le.escritorBloqueado(2)
le.leitorLendo(4)
le.leitorLendo(1)
# A variavel vale 3
le.leitorSaindo(1)
le.escritorBloqueado(1)
# A variavel eh impar.
le.leitorSaindo(1)
# A variavel eh impar.
le.leitorSaindo(3)
# A variavel eh impar.
le.leitorSaindo(4)
le.escritorEscrevendo(3)
le.leitorBloqueado(2)
le.escritorSaindo(3)
le.escritorEscrevendo(2)
le.leitorBloqueado(2)
le.escritorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.leitorLendo(2)
le.leitorLendo(1)
le.escritorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
# A variavel eh impar.
le.leitorSaindo(1)
# A variavel eh impar.
le.leitorSaindo(2)
le.escritorEscrevendo(1)
le.leitorBloqueado(3)
le.escritorSaindo(1)
le.escritorEscrevendo(2)
le.leitorBloqueado(3)
le.escritorBloqueado(1)
le.leitorBloqueado(1)
le.leitorBloqueado(3)
le.escritorSaindo(2)
le.leitorLendo(3)
# A variavel vale 2
le.leitorLendo(3)
le.leitorLendo(1)
le.escritorBloqueado(1)
le.leitorSaindo(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
# A variavel eh par.
le.leitorSaindo(1)
# A variavel eh par.
le.leitorSaindo(3)
le.escritorEscrevendo(1)
le.escritorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(3)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.escritorBloqueado(3)
le.escritorBloqueado(1)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(3)
le.leitorLendo(4)
le.leitorLendo(1)
le.escritorBloqueado(2)
le.escritorBloqueado(1)
le.escritorBloqueado(3)
le.leitorLendo(2)
le.leitorLendo(2)
# A variavel vale 3
le.leitorSaindo(2)
le.escritorBloqueado(2)
le.leitorLendo(1)
# A variavel vale 3
le.leitorSaindo(1)
le.escritorBloqueado(1)
# A variavel eh impar.
le.leitorSaindo(1)
# A variavel eh impar.
le.leitorSaindo(2)
# A variavel eh impar.
le.leitorSaindo(4)
le.escritorEscrevendo(2)
le.escritorSaindo(2)
le.escritorEscrevendo(1)
le.escritorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(3)